#!/bin/env ruby
require 'rubygems'
require 'yajl'
require 'ruote'
require 'ruote/storage/fs_storage'

engine = Ruote::Engine.new(
    # Use boss.config
    Ruote::FsStorage.new('/var/spool/boss/boss_ruote_db/')
)

statuses = engine.processes

statuses.each { |p|
  if (ARGV[0] == p.definition_name or
      ARGV[0] == p.wfid or
      ARGV[0] == p.position == ARGV[0]) then
    puts "killing #{p.definition_name} : #{p.wfid}"
    engine.kill( p.wfid )
  end
}
