#!/usr/bin/env ruby
require 'rubygems'
require 'yajl'
require 'ruote'
require 'ruote/storage/fs_storage'

engine = Ruote::Engine.new(
    # Use boss.config
    Ruote::FsStorage.new('/var/spool/boss/boss_ruote_db/')
)


engine.process_ids.each { |pid|
  p = engine.process(pid)
  puts "looking at #{p.definition_name}"
  if (ARGV[0] == p.definition_name or
      ARGV[0] == p.wfid or
      ARGV[0] == p.position) then
    puts "killing #{p.definition_name} : #{p.wfid}"
    engine.kill( p.wfid )
  end
}
