source "http://rubygems.org"
gem "rspec", :require => "spec" 
gem "inifile"
gem "ruote-amqp", :git => "https://github.com/MeeGoIntegration/ruote-amqp.git", :branch => "ack"
gem "ruote-kit", :git => "https://github.com/kennethkalmer/ruote-kit.git", :branch => "master"
gem "yajl-ruby"
gem "ruote", :git => "https://github.com/jmettraux/ruote.git", :branch => "master"
gem "rufus-cloche", :git => "https://github.com/MeeGoIntegration/rufus-cloche.git", :branch => "devel"
gem "amqp"
