#!/bin/sh
[ -f /etc/default/boss ] && . /etc/default/boss
[ -f /etc/sysconfig/boss ] && . /etc/sysconfig/boss

exec 2>&1
# Make some environment variables available to boss
export HOME=`eval echo ~$SERVER_USER`
export SERVER_DATABASE
exec setuidgid $SERVER_USER /usr/lib/boss/boss-daemon.rb
