source "http://rubygems.org"
gem 'daemon-kit', :path => "../ruote/daemon-kit"
gem 'amqp', :git =>"git://github.com/tmm1/amqp.git"
gem 'ruote', :path => "../ruote/ruote"
gem 'ruote-amqp', :path => "../ruote/ruote-amqp"
gem 'rspec'
gem 'eventmachine'
gem 'json'
gem 'yajl-ruby'